//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Web.UI.Staff {
    
    
    public partial class CreateAssesment {
        
        /// <summary>
        /// HeaderContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LMS_Web.UserControls.HeaderContent HeaderContent;
        
        /// <summary>
        /// WebUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LMS_Web.Master_Template.Trainer.WebUserControl1 WebUserControl1;
    }
}
